#!/usr/bin/env bash

# Change current working directory to the directory of this script
cd $(dirname "$0")

if [ ! -f .env ]; then
    echo "The .env file required for deployment does not exist."
    exit
fi

source .env

if [ "$NODE_ENV" == "development" ]; then
    echo "The deployment will only be executed if the value of NODE_ENV is not 'development'."
    exit
fi

git fetch origin master

LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse origin/master)

if [ "$LOCAL" == "$REMOTE" ]; then
    echo "✅ Already up to date. No deployment needed."
    exit 0
fi

git reset --hard
git clean -d -f
git pull origin master --rebase

npm ci --audit false
npm run generate

echo "🚀 Application deployed!"